/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: kmichy (https://sketchfab.com/kmichy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/red-leather-jacket-33e80ed4b76d4a8397e669ce66493374
Title: Red Leather Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.Jacket_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
        <mesh geometry={nodes.Tshirt_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
        <mesh geometry={nodes.Epaulette1_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
        <mesh geometry={nodes.Epaulette2_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
        <mesh geometry={nodes.Buttons_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
        <mesh geometry={nodes.Zipper_low_LeatherJacket_Mat1_0.geometry} material={materials.LeatherJacket_Mat1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
