/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf 
Author: DerekHill1 (https://sketchfab.com/DerekHill1)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/wool-jacket-09bdd9d188e9405b88bbafdbbffbd93d
Title: Wool Jacket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.237}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_4.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_5.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_6.geometry} material={materials.jacket_basic} />
          <mesh geometry={nodes.defaultMaterial_7.geometry} material={materials.jacket_basic} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('wool_jacket/scene.gltf')
